name: Send SMS
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: 'registry setup'
              uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com/
                  scope: '@varunnayal'
            - name: install
              run: npm ci
            - name: build
              if: success()
              run: npm run build
            - name: cat
              run: cat  /home/runner/work/_temp/.npmrc
            - name: echo
              run: node -e "console.log(\"${{ secrets.GITHUB_TOKEN }}\".length, \"${{ secrets.GITHUB_TOKEN }}\")"
            - name: semantic-release
              if: success()
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: cat /home/runner/work/_temp/.npmrc && px semantic-release --debug